packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@swc/core': set this to true or false
  esbuild: true
  prisma: set this to true or false
  sharp: set this to true or false
